/******************************************************************************
 * This work is applicable to the conditions of the MIT License,              *
 * which can be found in the LICENSE file, or at                              *
 * https://github.com/philippwinter/pacman/blob/master/LICENSE                *
 *                                                                            *
 * Copyright (c) 2013 Philipp Winter, Jonas Heidecke & Niklas Kaddatz         *
 ******************************************************************************/

package model.container;

import model.Map;
import model.Position;

import java.util.Vector;
import java.util.Iterator;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Container for multiple {@link Position}s, where there are width*height {@link Position} objects indexed by Strings
 * generated by their unique coordinates (x, y).
 *
 * @author Philipp Winter
 * @author Jonas Heidecke
 * @author Niklas Kaddatz
 */
public class PositionContainer implements Container<Position> {

    private ConcurrentHashMap<String, Position> positions;

    private final int width;

    private final int height;

    public PositionContainer(int width, int height) {
        this.positions = new ConcurrentHashMap<>(width * height);
        this.width = width;
        this.height = height;
    }

    /**
     * Retrieve a position by it's x and y coordinates.
     *
     * @param x The x coordinate.
     * @param y The y coordinate.
     *
     * @return The position object.
     */
    public Position get(int x, int y) {
        Position val = positions.get(generateKey(x, y));
        if (val == null) {
            throw new IllegalArgumentException("The point " + x + "|" + y + " doesn't exist.");
        }
        return val;
    }

    @Override
    public Position get(int i) {
        // Not available here
        return null;
    }

    /**
     * Adds a position to the container. DO NOT USE THIS OUTSIDE {@link Map}.
     *
     * @param el The element to add.
     */
    @Override
    public void add(Position el) {
        this.positions.put(generateKey(el), el);
    }

    /**
     * Adds the elements of another container of the same type.
     *
     * @param container The other container.
     */
    @Override
    public void add(Container<Position> container) {
        for (Position p : container) {
            this.add(p);
        }
    }

    /**
     * Generate a key based on the supplied values.
     *
     * @param x The x coordinate.
     * @param y The y coordinate.
     *
     * @return The position object.
     */
    private String generateKey(int x, int y) {
        return x + "#" + y;
    }

    private String generateKey(Position pos) {
        return generateKey(pos.getX(), pos.getY());
    }

    public Vector<Position> getAll() {
        return new Vector<>(this.positions.values());
    }

    /**
     * Removes an element from the container.
     *
     * @param el The element to remove.
     */
    @Override
    public void remove(Position el) {
        this.positions.remove(generateKey(el.getX(), el.getY()));
    }

    @Override
    public Iterator<Position> iterator() {
        return positions.values().iterator();
    }

    @Override
    public boolean contains(Position p) {
        return this.positions.containsKey(this.generateKey(p));
    }

    @Override
    public int size() {
        return this.positions.size();
    }

    /**
     * Instantiate a new {@link PositionContainer} given two {@link Position}s, picking ones in the rectangle defined
     * by their coordinates.
     *
     * @param startPos the leftmost and lowest position to consider for the rectangle
     * @param endPos the rightmost and highest position to consider for the rectangle
     * @return A {@link PositionContainer} containing all Position objects in the rectangle
     */
    public PositionContainer getRange(Position startPos, Position endPos) {
        int startX = startPos.getX();
        int startY = startPos.getY();
        int endX = endPos.getX();
        int endY = endPos.getY();

        PositionContainer ret = new PositionContainer(width, height);

        for (int i = startX; i <= endX; i++) {
            for (int j = startY; j <= endY; j++) {
                ret.add(get(i, j));
            }
        }

        return ret;
    }

    public void removeAll() {
        this.positions.clear();
    }
}
